RezervacijaSoba/Models/Rezervacija.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RezervacijaSoba.Models
{
    public class Rezervacija
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string imeIPrezime { get; set; }

        [DataType(DataType.Date)]
        public DateTime DatumOd { get; set; }

        [DataType(DataType.Date)]
        public DateTime DatumDo { get; set; }

        public bool Otkazana { get; set; }

        public int SobaRezervacijeId { get; set; }

        [ForeignKey("SobaRezervacijeId")]
        public Soba SobaRezervacije { get; set; }
    }
}

RezervacijaSoba/Controllers/RezervacijasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using RezervacijaSoba.Models;

namespace RezervacijaSoba.Controllers
{
    public class RezervacijasController : Controller
    {
        private SmestajContext db = new SmestajContext();

        public static List<string> SortTypes = new List<string>
        {
            "Broj Kreveta" ,
            "Broj Kreveta Descending",
            "Cena Nocenja",
            "Cena Nocenja Descending",
        };

        private int itemsPerPage = 3;

        // GET: Rezervacijas
        public ActionResult Index(string sortType = "Broj Kreveta", int page = 1)
        {
            IQueryable<Rezervacija> rezervacijas = db.rezervacijas.Include(r => r.SobaRezervacije);

            switch (sortType)
            {
                case "Broj Kreveta":
                    rezervacijas = rezervacijas.OrderBy(x => x.SobaRezervacije.BrojKreveta);
                    break;
                case "Broj Kreveta Descending":
                    rezervacijas = rezervacijas.OrderByDescending(x => x.SobaRezervacije.BrojKreveta);
                    break;
                case "Cena Nocenja":
                    rezervacijas = rezervacijas.OrderBy(x => x.SobaRezervacije.CenaNocenja);
                    break;
                case "Cena Nocenja Descending":
                    rezervacijas = rezervacijas.OrderByDescending(x => x.SobaRezervacije.CenaNocenja);
                    break;
            }

            ViewBag.sortTypes = new SelectList(SortTypes, sortType);
            ViewBag.CurrentSortType = sortType;

            return View(rezervacijas.ToPagedList(page, itemsPerPage));
        }

        // GET: Rezervacijas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.rezervacijas.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }

        // GET: Rezervacijas/Create
        public ActionResult Create(int? id)
        {
            if (id != null)
            {
                Soba s = db.Sobas.Find(id);
                List<Soba> soba = new List<Soba>();
                soba.Add(s);
                ViewBag.SobaRezervacijeId = new SelectList(soba, "Id", "BrojSobe");
            }
            else
            {
                ViewBag.SobaRezervacijeId = new SelectList(db.Sobas, "Id", "BrojSobe");
            }
            return View();
        }

        // POST: Rezervacijas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,imeIPrezime,DatumOd,DatumDo,Otkazana,SobaRezervacijeId")] Rezervacija rezervacija)
        {
            if (ModelState.IsValid)
            {
                db.rezervacijas.Add(rezervacija);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SobaRezervacijeId = new SelectList(db.Sobas, "Id", "Id", rezervacija.SobaRezervacijeId);
            return View(rezervacija);
        }

        // GET: Rezervacijas/Edit/5
        public ActionResult Edit(int? id, int? sid)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.rezervacijas.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }

            if (sid != null)
            {
                Soba s = db.Sobas.Find(id);
                List<Soba> soba = new List<Soba>();
                soba.Add(s);
                ViewBag.SobaRezervacijeId = new SelectList(soba, "Id", "BrojSobe");
            }
            else
            {
                ViewBag.SobaRezervacijeId = new SelectList(db.Sobas, "Id", "BrojSobe", rezervacija.SobaRezervacijeId);
            }
            return View(rezervacija);

        }

        // POST: Rezervacijas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,imeIPrezime,DatumOd,DatumDo,Otkazana,SobaRezervacijeId")] Rezervacija rezervacija)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rezervacija).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SobaRezervacijeId = new SelectList(db.Sobas, "Id", "Id", rezervacija.SobaRezervacijeId);
            return View(rezervacija);
        }

        // GET: Rezervacijas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.rezervacijas.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }

        // POST: Rezervacijas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rezervacija rezervacija = db.rezervacijas.Find(id);
            db.rezervacijas.Remove(rezervacija);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Filter:
        [HttpPost]
        public ActionResult Filter(RezervacijaFilter filter)
        {
            IQueryable<Rezervacija> rezervacijas = db.rezervacijas.Include(r => r.SobaRezervacije);

            if (filter.RezervacijaDatumOd != null && filter.RezervacijaDatumOd != DateTime.MinValue)
            {
                rezervacijas = rezervacijas.Where(s => s.DatumOd >= filter.RezervacijaDatumOd);
            }

            if (filter.RezervacijaDatumDo != null && filter.RezervacijaDatumDo != DateTime.MinValue)
            {
                rezervacijas = rezervacijas.Where(s => s.DatumDo <= filter.RezervacijaDatumDo);
            }

            if (filter.BrojSobeRezervacije != null)
            {
                rezervacijas = rezervacijas.Where(p => p.SobaRezervacije.BrojSobe == filter.BrojSobeRezervacije);
            }

            var rezervacijeKojeNisuOtkazane = rezervacijas.Where(x => x.Otkazana == false); // ako nisu soft deleted

            if (rezervacijeKojeNisuOtkazane.Any()) // ukoliko ih ima da nisu otkazane u listi vraca view sa listom
            {
                return View(rezervacijeKojeNisuOtkazane.ToList());
            }
            TempData["NemaZadatogKriterijuma"] = "Izaberite drugacije vrednosti u filteru, padaci po ovom kriterijumu ne postoje u bazi!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RezervacijaSoba/Controllers/SmestajsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RezervacijaSoba.Models;
using Microsoft.Ajax.Utilities;
using PagedList;

namespace RezervacijaSoba.Controllers
{
    public class SmestajsController : Controller
    {
        private SmestajContext db = new SmestajContext();

        public enum SortTypes
        {
            Naziv,
            NazivDesc,
            Ocena,
            OcenaDesc,
        };

        public static Dictionary<string, SortTypes> SortTypeDict = new Dictionary<string, SortTypes>
        {
            {"Naziv" , SortTypes.Naziv },
            {"Naziv Descending" , SortTypes.NazivDesc },
            {"Ocena" , SortTypes.Ocena },
            {"Ocena Descending" , SortTypes.OcenaDesc },
        };

        public static List<string> SortTypesSoba = new List<string>
        {
            "Broj Kreveta" ,
            "Broj Kreveta Descending",
            "Cena Nocenja",
            "Cena Nocenja Descending",
        };

        private int itemsPerPage = 3;

        // GET: Smestajs
        public ActionResult Index(string search, string sortType = "Naziv", int page = 1)
        {
            SortTypes sortBy = SortTypeDict[sortType];

            IQueryable<Smestaj> smestajs = db.Smestajs;

            //Pretraživanje po nazivu, adresi i opisu:
            if (!search.IsNullOrWhiteSpace())
            {
                smestajs = smestajs.Where(
                    p => p.Naziv.Contains(search) ||
                    p.Adresa.Contains(search) ||
                    p.Opis.Contains(search));
            }
            //

            switch (sortBy)
            {
                case SortTypes.Naziv:
                    smestajs = smestajs.OrderBy(x => x.Naziv);
                    break;
                case SortTypes.NazivDesc:
                    smestajs = smestajs.OrderByDescending(x => x.Naziv);
                    break;
                case SortTypes.Ocena:
                    smestajs = smestajs.OrderBy(x => x.Ocena);
                    break;
                case SortTypes.OcenaDesc:
                    smestajs = smestajs.OrderByDescending(x => x.Ocena);
                    break;
            }

            ViewBag.sortTypes = new SelectList(SortTypeDict, "Key", "Key", sortType);
            ViewBag.CurrentSortType = sortType;


            return View(smestajs.ToPagedList(page, itemsPerPage));
        }

        // GET: Smestajs/Details/5
        public ActionResult Details(int? id, string sortTypeSoba = "Broj Kreveta")
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Smestaj smestaj = db.Smestajs.Find(id);
            if (smestaj == null)
            {
                return HttpNotFound();
            }

            IQueryable<Soba> sobas = db.Sobas.Include(s => s.SmestajSoba);

            switch (sortTypeSoba)
            {
                case "Broj Kreveta":
                    sobas = sobas.OrderBy(x => x.BrojKreveta);
                    break;
                case "Broj Kreveta Descending":
                    sobas = sobas.OrderByDescending(x => x.BrojKreveta);
                    break;
                case "Cena Nocenja":
                    sobas = sobas.OrderBy(x => x.CenaNocenja);
                    break;
                case "Cena Nocenja Descending":
                    sobas = sobas.OrderByDescending(x => x.CenaNocenja);
                    break;
            }

            ViewBag.sortTypes = new SelectList(SortTypesSoba, sortTypeSoba);
            ViewBag.CurrentSortType = sortTypeSoba;

            var sobe = sobas.ToList();

            return View(smestaj);
        }

        // GET: Smestajs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Smestajs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv,Opis,Adresa,Ocena")] Smestaj smestaj)
        {
            if (ModelState.IsValid)
            {
                db.Smestajs.Add(smestaj);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(smestaj);
        }

        // GET: Smestajs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Smestaj smestaj = db.Smestajs.Find(id);
            if (smestaj == null)
            {
                return HttpNotFound();
            }
            return View(smestaj);
        }

        // POST: Smestajs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naziv,Opis,Adresa,Ocena")] Smestaj smestaj)
        {
            if (ModelState.IsValid)
            {
                db.Entry(smestaj).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(smestaj);
        }

        // GET: Smestajs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Smestaj smestaj = db.Smestajs.Find(id);
            if (smestaj == null)
            {
                return HttpNotFound();
            }
            return View(smestaj);
        }

        // POST: Smestajs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Smestaj smestaj = db.Smestajs.Find(id);
            db.Smestajs.Remove(smestaj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Filter:
        [HttpPost]
        public ActionResult Filter(SmestajFilter filter)
        {
            IQueryable<Smestaj> smestajs = db.Smestajs;

            if (!filter.SmestajNaziv.IsNullOrWhiteSpace())
            {
                smestajs = smestajs.Where(s => s.Naziv.Contains(filter.SmestajNaziv));
            }

            if (!filter.SmestajAdresa.IsNullOrWhiteSpace())
            {
                smestajs = smestajs.Where(s => s.Adresa.Contains(filter.SmestajAdresa));
            }

            return View(smestajs.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RezervacijaSoba/Views/Rezervacijas/Create.cshtml
@model RezervacijaSoba.Models.Rezervacija

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Rezervacija</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.imeIPrezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imeIPrezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imeIPrezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumOd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumOd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumOd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumDo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumDo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumDo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Otkazana, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Otkazana)
                    @Html.ValidationMessageFor(model => model.Otkazana, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SobaRezervacijeId, "SobaRezervacijeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SobaRezervacijeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SobaRezervacijeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RezervacijaSoba/Views/Rezervacijas/Delete.cshtml
@model RezervacijaSoba.Models.Rezervacija

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rezervacija</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SobaRezervacije.BrojSobe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SobaRezervacije.BrojSobe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imeIPrezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imeIPrezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumOd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumOd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumDo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumDo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Otkazana)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Otkazana)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RezervacijaSoba/Views/Rezervacijas/Details.cshtml
@model RezervacijaSoba.Models.Rezervacija

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Rezervacija</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SobaRezervacije.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SobaRezervacije.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imeIPrezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imeIPrezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumOd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumOd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumDo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumDo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Otkazana)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Otkazana)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RezervacijaSoba/Views/Rezervacijas/Edit.cshtml
@model RezervacijaSoba.Models.Rezervacija

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Rezervacija</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.imeIPrezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imeIPrezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imeIPrezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumOd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumOd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumOd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumDo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumDo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumDo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Otkazana, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Otkazana)
                    @Html.ValidationMessageFor(model => model.Otkazana, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SobaRezervacijeId, "SobaRezervacijeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SobaRezervacijeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SobaRezervacijeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RezervacijaSoba/Views/Rezervacijas/Filter.cshtml
@model IEnumerable<RezervacijaSoba.Models.Rezervacija>

<h2>Filter</h2>
@Html.ActionLink("Go Back", "Index")

@{
    Html.RenderPartial("_RezervacijaTable");
}

RezervacijaSoba/Views/Rezervacijas/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<RezervacijaSoba.Models.Rezervacija>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-lg" })
    @Html.ActionLink("Povratak na glavni meni", "Index", "Smestajs", null, new { @class = "btn btn-primary btn-lg" })
    <button id="filter" class="btn btn-default btn-lg pull-right">Filter</button>
</p>

@*Skrivena forma koja se pojavljuje i nesaje (dodaje se i ukida klasa hidden) pritiskom na
    dugme Filter a posredstvom java scripta iz MyFilter.js:*@
<div id="filterForm" class="hidden">

    @using (Html.BeginForm("Filter", "Rezervacijas", FormMethod.Post))
    {
        @Html.Label("Datum početka rezervacije")
        @Html.TextBox("RezervacijaDatumOd", null, new { @class = "form-control" })
        @Html.Label("Datum kraja rezervacije")
        @Html.TextBox("RezervacijaDatumDo", null, new { @class = "form-control" })
        @Html.Label("Broj sobe za rezervacijeu")
        @Html.TextBox("BrojSobeRezervacije", null, new { @class = "form-control" })

        <input type="submit" value="Send" class="btn btn-info" />
    }

</div>


@*Sortiranje rezervacija:*@
<div class="well clearfix">

    <div class="col-md-6">
        <span>Sort rezervacija:</span>
        @using (Html.BeginForm("Index", "Rezervacijas", FormMethod.Get))
        {
            @Html.DropDownList("SortType", ViewBag.SortTypes as SelectList, new { @class = "form-control col-md-6" })
            <input type="submit" value="Sort" class="btn btn-warning" />
        }
    </div>
</div>

@{
    Html.RenderPartial("_RezervacijaTable");
}

@*Ubacivanje MyFilter.js u kome se nalazi logika za pokazivanje i skrivanje filterForm*@
@section scripts
{
    <script src="~/Scripts/MyFilter.js"></script>
}

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

RezervacijaSoba/Views/Rezervacijas/_RezervacijaTable.cshtml
@model IEnumerable<RezervacijaSoba.Models.Rezervacija>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SobaRezervacije.BrojSobe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.imeIPrezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumOd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumDo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Otkazana)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SobaRezervacije.BrojSobe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.imeIPrezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumOd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumDo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Otkazana)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>