RezervacijaSoba/Models/Soba.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RezervacijaSoba.Models
{
    public class Soba
    {
        public int Id { get; set; }

        public int BrojSobe { get; set; }

        public int BrojKreveta { get; set; }

        public double CenaNocenja { get; set; }

        public int SmestajSobaId { get; set; }

        [ForeignKey("SmestajSobaId")]
        public Smestaj SmestajSoba { get; set; }

        public List<Rezervacija> RezervacijeSoba { get; set; }

    }
}

RezervacijaSoba/Controllers/SmestajsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RezervacijaSoba.Models;
using Microsoft.Ajax.Utilities;
using PagedList;

namespace RezervacijaSoba.Controllers
{
    public class SmestajsController : Controller
    {
        private SmestajContext db = new SmestajContext();

        public enum SortTypes
        {
            Naziv,
            NazivDesc,
            Ocena,
            OcenaDesc,
        };

        public static Dictionary<string, SortTypes> SortTypeDict = new Dictionary<string, SortTypes>
        {
            {"Naziv" , SortTypes.Naziv },
            {"Naziv Descending" , SortTypes.NazivDesc },
            {"Ocena" , SortTypes.Ocena },
            {"Ocena Descending" , SortTypes.OcenaDesc },
        };

        public static List<string> SortTypesSoba = new List<string>
        {
            "Broj Kreveta" ,
            "Broj Kreveta Descending",
            "Cena Nocenja",
            "Cena Nocenja Descending",
        };

        private int itemsPerPage = 3;

        // GET: Smestajs
        public ActionResult Index(string search, string sortType = "Naziv", int page = 1)
        {
            SortTypes sortBy = SortTypeDict[sortType];

            IQueryable<Smestaj> smestajs = db.Smestajs;

            //Pretraživanje po nazivu, adresi i opisu:
            if (!search.IsNullOrWhiteSpace())
            {
                smestajs = smestajs.Where(
                    p => p.Naziv.Contains(search) ||
                    p.Adresa.Contains(search) ||
                    p.Opis.Contains(search));
            }
            //

            switch (sortBy)
            {
                case SortTypes.Naziv:
                    smestajs = smestajs.OrderBy(x => x.Naziv);
                    break;
                case SortTypes.NazivDesc:
                    smestajs = smestajs.OrderByDescending(x => x.Naziv);
                    break;
                case SortTypes.Ocena:
                    smestajs = smestajs.OrderBy(x => x.Ocena);
                    break;
                case SortTypes.OcenaDesc:
                    smestajs = smestajs.OrderByDescending(x => x.Ocena);
                    break;
            }

            ViewBag.sortTypes = new SelectList(SortTypeDict, "Key", "Key", sortType);
            ViewBag.CurrentSortType = sortType;


            return View(smestajs.ToPagedList(page, itemsPerPage));
        }

        // GET: Smestajs/Details/5
        public ActionResult Details(int? id, string sortTypeSoba = "Broj Kreveta")
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Smestaj smestaj = db.Smestajs.Find(id);
            if (smestaj == null)
            {
                return HttpNotFound();
            }

            IQueryable<Soba> sobas = db.Sobas.Include(s => s.SmestajSoba);

            switch (sortTypeSoba)
            {
                case "Broj Kreveta":
                    sobas = sobas.OrderBy(x => x.BrojKreveta);
                    break;
                case "Broj Kreveta Descending":
                    sobas = sobas.OrderByDescending(x => x.BrojKreveta);
                    break;
                case "Cena Nocenja":
                    sobas = sobas.OrderBy(x => x.CenaNocenja);
                    break;
                case "Cena Nocenja Descending":
                    sobas = sobas.OrderByDescending(x => x.CenaNocenja);
                    break;
            }

            ViewBag.sortTypes = new SelectList(SortTypesSoba, sortTypeSoba);
            ViewBag.CurrentSortType = sortTypeSoba;

            var sobe = sobas.ToList();

            return View(smestaj);
        }

        // GET: Smestajs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Smestajs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv,Opis,Adresa,Ocena")] Smestaj smestaj)
        {
            if (ModelState.IsValid)
            {
                db.Smestajs.Add(smestaj);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(smestaj);
        }

        // GET: Smestajs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Smestaj smestaj = db.Smestajs.Find(id);
            if (smestaj == null)
            {
                return HttpNotFound();
            }
            return View(smestaj);
        }

        // POST: Smestajs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naziv,Opis,Adresa,Ocena")] Smestaj smestaj)
        {
            if (ModelState.IsValid)
            {
                db.Entry(smestaj).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(smestaj);
        }

        // GET: Smestajs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Smestaj smestaj = db.Smestajs.Find(id);
            if (smestaj == null)
            {
                return HttpNotFound();
            }
            return View(smestaj);
        }

        // POST: Smestajs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Smestaj smestaj = db.Smestajs.Find(id);
            db.Smestajs.Remove(smestaj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Filter:
        [HttpPost]
        public ActionResult Filter(SmestajFilter filter)
        {
            IQueryable<Smestaj> smestajs = db.Smestajs;

            if (!filter.SmestajNaziv.IsNullOrWhiteSpace())
            {
                smestajs = smestajs.Where(s => s.Naziv.Contains(filter.SmestajNaziv));
            }

            if (!filter.SmestajAdresa.IsNullOrWhiteSpace())
            {
                smestajs = smestajs.Where(s => s.Adresa.Contains(filter.SmestajAdresa));
            }

            return View(smestajs.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RezervacijaSoba/Controllers/SobasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using PagedList;
using RezervacijaSoba.Models;

namespace RezervacijaSoba.Controllers
{
    public class SobasController : Controller
    {
        private SmestajContext db = new SmestajContext();

        public static List<string> SortTypes = new List<string>
        {
            "Broj Kreveta" ,
            "Broj Kreveta Descending",
            "Cena Nocenja",
            "Cena Nocenja Descending",
        };

        private int itemsPerPage = 3;

        // GET: Sobas
        public ActionResult Index(string sortType = "Broj Kreveta", int page = 1)
        {   
            IQueryable<Soba> sobas = db.Sobas.Include(s => s.SmestajSoba);

            switch (sortType)
            {
                case "Broj Kreveta":
                    sobas = sobas.OrderBy(x => x.BrojKreveta);
                    break;
                case"Broj Kreveta Descending":
                    sobas = sobas.OrderByDescending(x => x.BrojKreveta);
                    break;
                case "Cena Nocenja":
                    sobas = sobas.OrderBy(x => x.CenaNocenja);
                    break;
                case "Cena Nocenja Descending":
                    sobas = sobas.OrderByDescending(x => x.CenaNocenja);
                    break;
            }

            ViewBag.sortTypes = new SelectList(SortTypes, sortType);
            ViewBag.CurrentSortType = sortType;

            return View(sobas.ToPagedList(page, itemsPerPage));
        }

        // GET: Sobas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soba soba = db.Sobas.Find(id);
            if (soba == null)
            {
                return HttpNotFound();
            }
            var rezervacije = db.rezervacijas.ToList(); //Ovo dodaje sobe za prikaz u detalje od smeštaja

            return View(soba);
        }

        // GET: Sobas/Create
        public ActionResult Create(int? id)
        {
                    if (id != null)
            {
                Smestaj s = db.Smestajs.Find(id);
                List<Smestaj> smestaj = new List<Smestaj>();
                smestaj.Add(s);
                ViewBag.SmestajSobaId = new SelectList(smestaj, "Id", "Naziv");
            }
            else
            {
                ViewBag.SmestajSobaId = new SelectList(db.Smestajs, "Id", "Naziv");
            }
            return View();
        }

        // POST: Sobas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,BrojSobe,BrojKreveta,CenaNocenja,SmestajSobaId,Otkazana")] Soba soba)
        {
            if (ModelState.IsValid)
            {
                db.Sobas.Add(soba);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SmestajSobaId = new SelectList(db.Smestajs, "Id", "Naziv", soba.SmestajSobaId);
            return View(soba);
        }

        // GET: Sobas/Edit/5
        public ActionResult Edit(int? id, int? sid)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soba soba = db.Sobas.Find(id);
            if (soba == null)
            {
                return HttpNotFound();
            }

            if (sid != null)
            {
                Smestaj s = db.Smestajs.Find(id);
                List<Smestaj> smestaj = new List<Smestaj>();
                smestaj.Add(s);
                ViewBag.SmestajSobaId = new SelectList(smestaj, "Id", "Naziv");
            }
            else
            {
                ViewBag.SmestajSobaId = new SelectList(db.Smestajs, "Id", "Naziv", soba.SmestajSobaId);
            }
            return View(soba);
        }

        // POST: Sobas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BrojSobe,BrojKreveta,CenaNocenja,SmestajSobaId,Otkazana")] Soba soba)
        {
            if (ModelState.IsValid)
            {
                db.Entry(soba).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SmestajSobaId = new SelectList(db.Smestajs, "Id", "Naziv", soba.SmestajSobaId);
            return View(soba);
        }

        // GET: Sobas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soba soba = db.Sobas.Find(id);
            if (soba == null)
            {
                return HttpNotFound();
            }
            return View(soba);
        }

        // POST: Sobas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Soba soba = db.Sobas.Find(id);
            db.Sobas.Remove(soba);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Filter:
        [HttpPost]
        public ActionResult Filter(SobaFilter filter)
        {
            IQueryable<Soba> sobas = db.Sobas.Include(s => s.SmestajSoba);

            if (filter.SobaBrojKreveta != null)
            {
                sobas = sobas.Where(s => s.BrojKreveta == filter.SobaBrojKreveta);
            }

            if (filter.SobaCenaNocenja != null)
            {
                sobas = sobas.Where(s => s.CenaNocenja == filter.SobaCenaNocenja);
            }

            if (!filter.SmestajSobe.IsNullOrWhiteSpace())
            {
                sobas = sobas.Where(p => p.SmestajSoba.Naziv.Contains(filter.SmestajSobe));
            }

            return View(sobas.ToList());
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RezervacijaSoba/Views/Sobas/Create.cshtml
@model RezervacijaSoba.Models.Soba

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Soba</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BrojSobe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojSobe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojSobe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojKreveta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojKreveta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojKreveta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CenaNocenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CenaNocenja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CenaNocenja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmestajSobaId, "SmestajSobaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SmestajSobaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SmestajSobaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RezervacijaSoba/Views/Sobas/Delete.cshtml
@model RezervacijaSoba.Models.Soba

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Soba</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SmestajSoba.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmestajSoba.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojSobe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojSobe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojKreveta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojKreveta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CenaNocenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CenaNocenja)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RezervacijaSoba/Views/Sobas/Details.cshtml
@model RezervacijaSoba.Models.Soba

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Soba</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SmestajSoba.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SmestajSoba.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojSobe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojSobe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojKreveta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojKreveta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CenaNocenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CenaNocenja)
        </dd>

    </dl>
    <p>
        @Html.ActionLink("Kreiraj novu rezervaciju", "Create", "Rezervacijas", new { id = Model.Id }, null)
    </p>
    <table class="table">
        <tr>
            <th>
                Broj sobe
            </th>
            <th>
                Ime i prezime
            </th>
            <th>
                Datum rezervacije od
            </th>
            <th>
                Datum rezervacije do
            </th>
            <th></th>
        </tr>

        @if (Model.RezervacijeSoba != null)
        {
            foreach (var item in Model.RezervacijeSoba)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.SobaRezervacije.BrojSobe)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.imeIPrezime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatumOd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatumDo)
                    </td>
                    <td>
                        @Html.ActionLink("Izmeni", "Edit", "Rezervacijas", new { id = item.Id, sid = Model.Id }, null) |
                        @Html.ActionLink("Detalji", "Details", "Rezervacijas", new { id = item.Id }, null) |
                        @Html.ActionLink("Obriši", "Delete", "Rezervacijas", new { id = item.Id }, null)
                    </td>
                </tr>
            }
        }

        </table>






























</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RezervacijaSoba/Views/Sobas/Edit.cshtml
@model RezervacijaSoba.Models.Soba

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Soba</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BrojSobe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojSobe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojSobe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojKreveta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojKreveta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojKreveta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CenaNocenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CenaNocenja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CenaNocenja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SmestajSobaId, "SmestajSobaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SmestajSobaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SmestajSobaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RezervacijaSoba/Views/Sobas/Filter.cshtml
@model IEnumerable<RezervacijaSoba.Models.Soba>
@{
    ViewBag.Title = "Filter";
}

<h2>Filter</h2>
@Html.ActionLink("Go Back", "Index")

@{
    Html.RenderPartial("_SobaTable");
}

RezervacijaSoba/Views/Sobas/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<RezervacijaSoba.Models.Soba>

@{

    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-lg" })
    @Html.ActionLink("Povratak na glavni meni", "Index", "Smestajs", null, new { @class = "btn btn-primary btn-lg" })
    <button id="filter" class="btn btn-default btn-lg pull-right">Filter</button>
</p>

@*Skrivena forma koja se pojavljuje i nesaje (dodaje se i ukida klasa hidden) pritiskom na
    dugme Filter a posredstvom java scripta iz MyFilter.js:*@
<div id="filterForm" class="hidden">

    @using (Html.BeginForm("Filter", "Sobas", FormMethod.Post))
    {
        @Html.Label("Broj kreveta")
        @Html.TextBox("SobaBrojKreveta", null, new { @class = "form-control" })
        @Html.Label("Cena noćenja")
        @Html.TextBox("SobaCenaNocenj", null, new { @class = "form-control" })
        @Html.Label("Smestaj u kome je soba")
        @Html.TextBox("SmestajSobe", null, new { @class = "form-control" })

        <input type="submit" value="Send" class="btn btn-info" />
    }

</div>

@*Sortiranje soba:*@
<div class="well clearfix">

    <div class="col-md-6">
        <span>Sort soba:</span>
        @using (Html.BeginForm("Index", "Sobas", FormMethod.Get))
        {
            @Html.DropDownList("SortType", ViewBag.SortTypes as SelectList, new { @class = "form-control col-md-6" })
            <input type="submit" value="Sort" class="btn btn-warning" />
        }
    </div>
</div>

@{
    Html.RenderPartial("_SobaTable");
}

@*Ubacivanje MyFilter.js u kome se nalazi logika za pokazivanje i skrivanje filterForm*@
@section scripts
{
    <script src="~/Scripts/MyFilter.js"></script>
}

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

RezervacijaSoba/Views/Sobas/_SobaTable.cshtml
@model IEnumerable<RezervacijaSoba.Models.Soba>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SmestajSoba.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrojSobe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrojKreveta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CenaNocenja)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SmestajSoba.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrojSobe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrojKreveta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CenaNocenja)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>